### ISSUE TITLE
[Suggestion] theme-park

### ISSUE THREAD

**Issue by deathbybandaid** [foxly-it/Mailcow-Darkmode#2]
If you aren't aware:

https://github.com/GilbN/theme.park/

is a great way to theme dashboards. If you converted this to a "base" css that followed that format, it would be easily capable of swapping between all the theme-park themes

**Comment by foxly-it** [comment]
Hello, I will think about it and possibly make a PR.

**Comment by foxly-it** [comment]
I decided against conversion. I am in the process of integrating a switch button and submitting a PR to Mailcow. I hope Mailcow will do the conversion then. 
I thank you anyway for the comment about Theme-Park
