### ISSUE TITLE
missing darkmode for Tags

### ISSUE THREAD

**Issue by T0biii** [foxly-it/Mailcow-Darkmode#3]
![image](https://user-images.githubusercontent.com/5702338/167117278-fb6fb6a6-bec0-46a6-aba2-e8912d584ca7.png)

`<input type="text" class="tag-input">`

**Comment by foxly-it** [comment]
Thanks, I will fix this with the next version.

**Comment by foxly-it** [comment]
Fixed with the current version.

**Comment by T0biii** [comment]
got still this after the update
![image](https://user-images.githubusercontent.com/5702338/168074963-fe68fdf5-1606-4a68-82ee-df7edd61a369.png)

**Comment by foxly-it** [comment]
Ok, on the local machine it worked. I'll adjust that again. Thanks for reporting

**Comment by T0biii** [comment]
on `/mailbox` its fixed correct, but under:
`/edit/domain/domain.tld` not. and if you want to add a new Domain and/or Mailbox

also under(OAuth2/edit -> `/edit.php?oauth2client=2`):
Client-ID, Client-Secret, Scope
![image](https://user-images.githubusercontent.com/5702338/168129774-cede4fc3-1de0-472d-806d-7f246e1efe54.png)
(UI-Anpassung)
![image](https://user-images.githubusercontent.com/5702338/168130052-471c1b43-3538-44f1-973d-aaa9d5d128cb.png)

**Comment by foxly-it** [comment]
@T0biii 
I should have everything revised, could you test the new release once?

**Comment by T0biii** [comment]
thanks seems good now

**Comment by T0biii** [comment]
oh found some more:
`/admin`
![image](https://user-images.githubusercontent.com/5702338/168807917-873e2ddb-2792-46a3-8763-60bb30aaa2d6.png)
`/quarantine` Details
![image](https://user-images.githubusercontent.com/5702338/168808122-41826efe-6dfe-41c7-840b-bbec184d6cdf.png)

**Comment by foxly-it** [comment]
Thanks for reporting. I'm sure I've reviewed this before :-/. Will look into it tonight as soon as I have time.

**Comment by T0biii** [comment]
no worries, it is not urgent 
still good work and many thanks for it

is there a change to get this upstream, so maybe some more mailcower can update it and it is there by default 
i think because `@media (prefers-color-scheme: dark)` got added you can have a good change for it?
and maybe someone can add a button or so to toggle it?

**Comment by foxly-it** [comment]
With the button would certainly work, but only via JS. Whether this is now update safe, I do not know. So that a change is possible, must also the CSS of the bright style in the file. I will see if this can be solved simply.

**Comment by foxly-it** [comment]
The Admin GUI is customized. Only the quarantine is missing, I will add that with the next release.

**Comment by foxly-it** [comment]
The adjustments are included in the latest released update. I'm currently trying to add a switch with JS, so that you can also manually switch between light and dark.
