### ISSUE TITLE
v2022 - 07 login menu

### ISSUE THREAD

**Issue by foxly-it** [foxly-it/Mailcow-Darkmode#4]
The new menu at the login for WebAuthn or TOTP has got a new CSS class and therefore has to be adapted to the darkmode.

**Comment by T0biii** [comment]
fyi: https://twitter.com/mailcow_email/status/1540375061231722498
they confirmed Darkmode support with BS5

**Comment by foxly-it** [comment]
Hi, I didn't get that at all. In which update is BootstrapV5 included?

**Comment by foxly-it** [comment]
I have installed the fix times, still without switch button

**Comment by T0biii** [comment]
> Hi, I didn't get that at all. In which update is BootstrapV5 included?

I is comming soon to the nightly build i guess.
To Test it.
